# Generated by Django 4.1.5 on 2023-01-21 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_created',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Builder', 'Builder'), ('Plumbing', 'Plumbing'), ('Carpentry', 'Carpentry'), ('Handyman', 'Handyman'), ('Electrician', 'Electrician')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_closed',
            field=models.DateField(default=datetime.datetime(2023, 1, 21, 2, 7, 47, 491793)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_work_starts',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 2, 8, 6, 406008)),
            preserve_default=False,
        ),
    ]
